Controllers/CartsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebShopping.Models;
using X.PagedList;

namespace WebShopping.Controllers
{
    public class CartsController : Controller
    {
        private WebShoppingContext db = new WebShoppingContext();

        // GET: Carts
        public ActionResult Index(int? page)
        {
            var cart = db.Carts.Include(c => c.Product);
            var carts = cart.ToList();
            decimal total = 0;

            foreach(var item in carts)
            {
                total += item.Product.Price * item.Quantity;
            }

            int pageSize = 4;
            int pageNumber = (page ?? 1);

            ViewBag.Total = total;

            return View(carts.ToPagedList(pageNumber, pageSize));
        }

        // POST: Carts/Create
        [HttpPost]
        public ActionResult Create([Bind(Include = "Id,ProductId,Quantity")] Cart cart)
        {
            var carts = db.Carts.ToList();
            var found = carts.FirstOrDefault(s => s.ProductId == cart.ProductId);

            if (found != null)
            {
                var item = found;
                item.Quantity += 1;

                db.Entry(item).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            if (ModelState.IsValid)
            {
                db.Carts.Add(cart);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return RedirectToAction("Index");
        }

        // POST: Carts/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ProductId, Quantity")] Cart cart)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cart).State = EntityState.Modified;
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        // POST: Carts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            if (ModelState.IsValid)
            {
                Cart cart = db.Carts.Find(id);
                db.Carts.Remove(cart);
                db.SaveChanges();
            }

            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebShopping.Models;
using X.PagedList;

namespace WebShopping.Controllers
{
    public class HomeController : Controller
    {
        private WebShoppingContext db = new WebShoppingContext();

        public ActionResult Index(int? page, string searchString, string sortBy, string category)
        {
            var products = db.Products.Include(p => p.Category);

            if (!String.IsNullOrEmpty(searchString))
            {
                products = products.Where(p => p.Title.Contains(searchString));
            }

            if(!String.IsNullOrEmpty(category) && !category.Equals("All"))
            {
                products = products.Where(p => p.Category.Title == category);
            }

            switch (sortBy)
            {
                case "IdASC":
                    products = products.OrderBy(p => p.Id);
                    break;
                case "IdDESC":
                    products = products.OrderByDescending(p => p.Id);
                    break;
                case "PriceASC":
                    products = products.OrderBy(p => p.Price);
                    break;
                case "PriceDESC":
                    products = products.OrderByDescending(p => p.Price);
                    break;
                default:
                    products = products.OrderByDescending(p => p.Id);
                    break;
            }


            // To reuse search string
            ViewBag.CategoryString = category;
            ViewBag.SortByString = sortBy;
            ViewBag.SearchString = searchString;

            // To render dropdown list
            ViewBag.Category = new SelectList(db.Categories, "Title", "Title");
            ViewBag.SortBy = new SelectList(db.Sorts, "Name", "DisplayName");

            

            int pageSize = 9;
            int pageNumber = (page ?? 1);

            return View(products.ToList().ToPagedList(pageNumber, pageSize));
        }

        
    }
}

Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebShopping.Models;

namespace WebShopping.Controllers
{
    public class ProductsController : Controller
    {
        private WebShoppingContext db = new WebShoppingContext();

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Include(p => p.Category).SingleOrDefault(p => p.Id == id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }
        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Home/Index.cshtml
@model X.PagedList.IPagedList<WebShopping.Models.Product>
@using X.PagedList.Mvc;
@using X.PagedList;
@using X.PagedList.Mvc.Bootstrap4;

@{
    ViewBag.Title = "Home Page";
}

<div class="row">
    <div class="col-lg-3">
        @using (Html.BeginForm("Index", "Home", FormMethod.Get))
        {
            <div class="form-group">
                <label for="search" class="sr-only">Search</label>
                <div class="input-group">
                    @Html.TextBox("SearchString", null, htmlAttributes: new { @class = "form-control", placeholder="Looking for ... "})
                    <div class="input-group-append">
                        <button type="submit" class="input-group-append btn btn-primary"><i class="fas fa-search"></i></button>
                    </div>
                </div>
            </div>
            <hr class="my-4" />
            <h4>Category</h4>
            <div class="form-group">
                <label for="categories" class="sr-only">Category</label>
                <div class="list-group">
                    <div class="sr-only" id="CurrentCategory">@ViewBag.CategoryString</div>
                    @Html.DropDownList("Category", null, htmlAttributes: new { @class = "form-control", onchange = "this.form.submit();" })
                </div>
            </div>

            <h4>Sort By</h4>
            <div class="form-group">
                <div class="list-group">
                    @Html.DropDownList("SortBy", null, htmlAttributes: new { @class = "form-control", onchange = "this.form.submit();" })
                </div>
            </div>
        }
    </div>
    <!-- /.col-lg-3 -->

    <div class="col-lg-9">
        @if (Model.Count() == 0)
        {
            <div class="alert alert-info text-center" role="alert">
                There is no item to display
            </div>
        }
        else
        {

            <div class="row">
                @foreach (var item in Model)
                {
                    <div class="col-lg-4 col-md-4 mb-4">
                        <div class="card h-100">
                            <a href="/Products/Details/@item.Id"><img class="card-img-top card-overview" src="@Html.DisplayFor(modelItem => item.ImageUrl)"></a>
                            <hr style="margin: 0;" />
                            <div class="card-body">
                                <h5 class="card-title">
                                    @Html.ActionLink(item.Title, "Details", "Products", new { id = item.Id }, null)
                                </h5>
                                <span class="badge badge-warning mb-2">@Html.DisplayFor(modelItem => item.Category.Title)</span><br />
                                <h5>$@Html.DisplayFor(modelItem => item.Price)</h5>
                            </div>
                            <div class="card-footer">
                                @using (Html.BeginForm("Create", "Carts"))
                                {
                                    @Html.AntiForgeryToken()
                                    @Html.Hidden("ProductId", item.Id);
                                    @Html.Hidden("Quantity", 1);
                                    <button type="submit" class="btn btn-primary">Add to Cart</button>
                                }
                            </div>
                        </div>
                    </div>
                }
            </div>
            <div class="pagination-center">
                @Html.PagedListPager((IPagedList)Model, page => Url.Action("Index", new { page, SearchString = ViewBag.SearchString, Category = ViewBag.CategoryString, SortBy = ViewBag.SortByString }), Bootstrap4PagedListRenderOptions.ClassicPlusFirstAndLast)
            </div>
        }
    </div>
    <!-- /.col-lg-9 -->
</div>
<!-- /.row -->